# Generated by Django 4.1.2 on 2022-10-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('photo', models.FileField(upload_to=None)),
                ('housename', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('panchayath', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('position_played', models.CharField(max_length=50)),
            ],
        ),
    ]
