# Generated by Django 4.1.2 on 2022-10-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='housename',
        ),
        migrations.RemoveField(
            model_name='student',
            name='post',
        ),
    ]
