# Generated by Django 4.1.2 on 2022-10-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_remove_student_housename_remove_student_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='housename',
            field=models.CharField(default=56, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='post',
            field=models.CharField(default=45, max_length=50),
            preserve_default=False,
        ),
    ]
