# Generated by Django 4.1.2 on 2022-10-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_student_housename_student_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
    ]
