# Generated by Django 4.1.2 on 2022-10-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_remove_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='position_played',
        ),
        migrations.AddField(
            model_name='student',
            name='position',
            field=models.CharField(default=45, max_length=50),
            preserve_default=False,
        ),
    ]
