# Generated by Django 4.1.2 on 2022-10-20 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_remove_student_position_played_student_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statictics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bollcontronl', models.IntegerField()),
                ('passaccuracy', models.IntegerField()),
                ('stamina', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('takles', models.IntegerField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.student')),
            ],
        ),
    ]
