# Generated by Django 4.1.2 on 2022-11-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_statictics'),
    ]

    operations = [
        migrations.AddField(
            model_name='statictics',
            name='shoot',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
