# Generated by Django 4.1.2 on 2022-11-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0008_alter_statictics_bollcontronl_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statictics',
            new_name='Statistics',
        ),
    ]
