# Generated by Django 4.1.2 on 2022-11-14 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0011_attendence_date_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='coach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coach.coach'),
            preserve_default=False,
        ),
    ]
