# Generated by Django 4.1.2 on 2022-11-14 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0012_student_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='coach',
        ),
    ]
